"""
geolonia/japanese-addresses（全国27万件の町丁目＋大字＋小字レベル）から、
OLD_TOWNS（旧町村名）と現行の字・大字・町丁目名の衝突セットを生成する。

目的:
  現行の "〇〇市" の "△△町" という町域や小字に OLD_TOWNS（旧町村名）と同名の地名が
  存在する場合、それは旧住所ではなく現行地名なので flag を立てない。
  ken_all だけでは大字・小字レベルの情報が薄いため、geolonia で補う。

出力:
  data/cities.js を追記更新（既存の oldTownConflicts を拡張）
  - "〇〇市|△△町" のように現行の (市区町村 + 大字町丁目) / (市区町村 + 小字) ペア

実行:
  python scripts/build_aza_conflicts.py
"""
from __future__ import annotations

import csv
import io
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = ROOT / "data" / "raw"
DATA_DIR = ROOT / "data"
HTML_PATH = ROOT / "index.html"
CITIES_JS = DATA_DIR / "cities.js"

GEOLONIA_URL = "https://geolonia.github.io/japanese-addresses/latest.csv"
GEOLONIA_CACHE = RAW_DIR / "geolonia_latest.csv"


def load_old_towns() -> list:
    content = HTML_PATH.read_text(encoding="utf-8")
    m = re.search(r"const OLD_TOWNS = \[([\s\S]*?)\];", content)
    if not m:
        return []
    return [x for x in re.findall(r'"([^"]+)"', m.group(1)) if x.strip()]


def download_geolonia() -> Path:
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    if GEOLONIA_CACHE.exists() and GEOLONIA_CACHE.stat().st_size > 10_000_000:
        print(f"[skip] already downloaded: {GEOLONIA_CACHE} ({GEOLONIA_CACHE.stat().st_size:,} bytes)")
        return GEOLONIA_CACHE
    print(f"[dl]   {GEOLONIA_URL}")
    req = urllib.request.Request(GEOLONIA_URL, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=300) as r, open(GEOLONIA_CACHE, "wb") as f:
        while True:
            chunk = r.read(1024 * 1024)
            if not chunk:
                break
            f.write(chunk)
    print(f"[ok]   saved {GEOLONIA_CACHE} ({GEOLONIA_CACHE.stat().st_size:,} bytes)")
    return GEOLONIA_CACHE


def iter_geolonia_rows(csv_path: Path):
    """geolonia CSV を都道府県名・市区町村名・大字町丁目名・小字通称名でイテレート"""
    with open(csv_path, encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader, None)
        for row in reader:
            if len(row) < 12:
                continue
            pref = row[1].strip()
            city = row[5].strip()
            oaza = row[8].strip()    # 大字町丁目名
            koaza = row[11].strip()  # 小字・通称名
            yield pref, city, oaza, koaza


def build_conflicts(geolonia_path: Path, old_towns: list) -> list:
    """OLD_TOWNS と同名の大字・小字が現行で存在する (city, old_town) ペアを収集"""
    old_set = set(old_towns)
    # 先頭一致も許すため、sort by length desc
    old_sorted = sorted(old_towns, key=len, reverse=True)

    conflict = set()  # {"〇〇市|△△町"}
    seen = 0
    for pref, city, oaza, koaza in iter_geolonia_rows(geolonia_path):
        seen += 1
        # oaza / koaza のいずれかが OLD_TOWNS に (等価 or 前方一致) するケースを拾う
        for field in (oaza, koaza):
            if not field:
                continue
            # 完全一致
            if field in old_set:
                conflict.add(f"{city}|{field}")
                continue
            # 前方一致（「新田町」が「新田町通」等のprefix）
            for ot in old_sorted:
                if field.startswith(ot):
                    conflict.add(f"{city}|{ot}")
                    break
    print(f"[info] scanned {seen:,} geolonia rows")
    return sorted(conflict)


def merge_into_cities_js(new_conflicts: list):
    """cities.js の oldTownConflicts に追加マージ（既存は保持）"""
    text = CITIES_JS.read_text(encoding="utf-8")
    m = re.search(r"window\.POSTAL_MASTER_CITIES\s*=\s*(\{[\s\S]*\});", text)
    if not m:
        raise RuntimeError("cities.js の構造を認識できませんでした")
    payload = json.loads(m.group(1))
    existing = set(payload.get("oldTownConflicts", []))
    merged = sorted(existing | set(new_conflicts))
    payload["oldTownConflicts"] = merged
    new_text = (
        "// Auto-generated by scripts/build_postal_master.py / build_aza_conflicts.py\n"
        "// Source: japanpost ken_all.zip + geolonia/japanese-addresses\n"
        "window.POSTAL_MASTER_CITIES = " + json.dumps(payload, ensure_ascii=False) + ";\n"
    )
    CITIES_JS.write_text(new_text, encoding="utf-8")
    print(f"[ok]   cities.js の oldTownConflicts: {len(existing):,} → {len(merged):,} (+{len(merged) - len(existing):,})")


def main():
    old_towns = load_old_towns()
    print(f"[info] OLD_TOWNS: {len(old_towns)} entries")
    geo_path = download_geolonia()
    conflicts = build_conflicts(geo_path, old_towns)
    print(f"[info] detected conflicts from geolonia: {len(conflicts):,}")
    merge_into_cities_js(conflicts)
    print("[done]")


if __name__ == "__main__":
    sys.exit(main())
